---
abstract: 'Catalan holidays'
author:
  - 'Miquel Ruiz <mruiz@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300005, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Date-Holidays-CA_ES
requires:
  Date::Holidays::ES: 0.02
resources:
  bugtracker: https://github.com/miquelruiz/Date-Holidays-CA_ES/issues
  repository: git://github.com/miquelruiz/Date-Holidays-CA_ES.git
version: 0.02
